### PR TITLE
Added error about granting permission

### PR DESCRIPTION
**Pull request by joshdholtz**
**Changes**
- Waits for "instruments" process to listen for a failure
  - Let's user know how to solve if the error involves granting permission
- Added some files to `.gitignore`
- Added shared Example scheme to example Xcode project

**How to test**
- Created a new user on my mac (testuser1)
- Added testuser1 to sudoers file (because I needed to install gems and sometimes delete things when I messed up)
- Cloned my fork
- Ran example project and saw failure but help message :tada: :confetti_ball: 

screen shot 2015-01-15 at 7 14 43 pm

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks @joshdholtz, that's a great pull request. 

Does `instruments` put out `Instruments wants permission to analyze other processes`? I haven't seen it before.

**Comment by KrauseFx** [comment]
Oh, it looks like you duplicated a scheme, I'll remove it again.

**Comment by joshdholtz** [comment]
@KrauseFx Yes sir, it does spit out that "wants permission to analyze other processes" message. I can verify on some co-workers machines today.

Also, the scheme thing was weird. I opened the project right after I cloned and it had a scheme but then for some reason it stopped showing it which is why I added it.

And thanks for the merge 😁

**Comment by KrauseFx** [comment]
Thanks again @joshdholtz, it looks great. I published a new version already! https://github.com/KrauseFx/snapshot/releases

**Pull request merged**
