### PR TITLE
Provide udid to callback

### PR DESCRIPTION
**Pull request by feralbob**
A quick and dirty method of providing the UDID to the callback, so that the Simulator can be reset if needed.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, thanks :+1:

**Comment by KrauseFx** [comment]
Oh, for your use case, it would have been enough to just use `booted`.

**Comment by KrauseFx** [comment]
example `com("xcrun simctl shutdown booted")`

**Comment by feralbob** [comment]
Oh really so booted gets translates to the currently running sim - nice
didn't know that.

Thanks

So yeah not sure if there is value in having the UDID or not in the
callback.  Might not be needed, so feel free to revert so it won't break
any user callbacks that they have already.

B

**Comment by feralbob** [comment]
Oh that didn't work....

victory:snapshot bob$ xcrun simctl erase booted

An error was encountered processing the command (code=146):

Unable to erase contents and settings in current state: Booted

I must just be confused :)

**Comment by KrauseFx** [comment]
Oh, makes sense, you can't erase a running simulator. Thanks :+1:

**Pull request merged**
