### PR TITLE
Images get rotated for landscape left, landscape, right, and portrait up...

### LINKED ISSUE #24: Rotate Landscape Screenshots
If one rotates the device to landscape, the screenshot is not automatically rotated. It would be nice if snapshot detected and rotated it. This is something that ui-screen-shooter does already.

To test, rotate device in the automation script via:

UIATarget.localTarget().setDeviceOrientation(UIA_DEVICE_ORIENTATION_LANDSCAPELEFT);

This could be implemented in the same way that ui-screen-shooter does it by running this command just prior to copying to the output screenshots directory: 

find $trace_results_dir/Run\ 1/ -name *landscape*png -type f -exec sips -r -90 \{\} \;

### PR DESCRIPTION
**Pull request by joshdholtz**
...side down oriented sceenshots

Closes https://github.com/KrauseFx/snapshot/issues/24
- Runs sips for doing image manipulation after all screenshots are taken
  - Rotates landscape left
  - Rotates landscape right
  - Rotates portrait upside down
  - Doc: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sips.1.html
- :warning:  Changed the way screenshots are name :warning: (I can change this back if you'd like) 
  - `var parts = [language, model, name, orientation];`
  - Allows for the files to be sorted by the name of the screenshot instead of the orientation

screen shot 2015-01-26 at 4 30 33 pm

### CODE REVIEW

**Comment by joshdholtz** [comment]
@KrauseFx Just added in the description that it should close https://github.com/KrauseFx/snapshot/issues/24

**Comment by joshdholtz** [comment]
@KrauseFx Updated!

**Comment by KrauseFx** [comment]
Thanks @joshdholtz for implementing this :+1:

**Comment by KrauseFx** [comment]
Oh, I haven't found a clean solution for it yet, so I forgot to also update the template, which is used when running `snapshot init`: https://github.com/KrauseFx/snapshot/commit/8d1345609df337a91c481557042baf216d04292d

**Comment by joshdholtz** [comment]
Ah, didn't know that existed 😇 I will remember that for next time

**Comment by joshdholtz** [comment]
And no problem! I'll make sure to keep them coming. This tool hits the sweet spot of exactly what I like to do ✊

**Pull request merged**
