### PR TITLE
Make 'build' an option that is default off

### PR DESCRIPTION
**Pull request by martingjaldbaek**
… in order to work around an issue where the run would fail immediately after building with "Test failed. Exit status: 65" on machines where building takes more than a couple minutes (on those slow machines, it will still fail the first time it is run since it must be built first, but can succeed on the second run, assuming the dependency check on the build cache doesn't take abnormally long). See issue #330 for more information.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Could we change the default to be just like it has been before? Or are you sure it's better like this?

**Comment by KrauseFx** [comment]
Sorry for the late reply btw

**Comment by martingjaldbaek** [comment]
Hey - no worries :) The way I saw it, from an API standpoint it seemed much cleaner to have a "build" option to opt into the workaround than to have a "nobuild" option to opt out of it. But on the other hand they're both ways of running onto Apple's bugs, so ideally either version would be redundant and should be removed if/when Apple gets around to fixing the bugs. My impression is that including 'build' by default has made it work out of the box more often on CI servers, but also causes it to fail every time on slow computers like mine, or large codebases that take a long time to compile in general. In the end, I'd say the weightiest question is "which default would make it 'just work' for the most users"? However, even when 'build' is not included, I still get a failure the first time the compilation happens (since it takes so long), but it succeeds on subsequent tests where the build cache is picked up instead. Which is not ideal, but beats not being able succeed at all. But I agree that this is an argument in favor of making a "-nobuild" option instead, since this solution isn't bulletproof either, and never "just works".

However, there's one thing I think would be worth investigating first - I'm wondering if there's a way to get the best of both worlds, so no option is needed at all: Maybe it would be possible, instead of running xcrun with the "test build" commands, it could be run twice in a row, first to build without testing and the second time to run the test, which should then pick up the build cache. That _should_ make it work in my case every time, so if that also works for the case that originally caused 'build' to be added, then it seems like the ideal workaround. I'm not really an expert on neither xcrun/xcodebuild nor Ruby, and I don't know how to repro the other case - but I thought I would mention it, since it seems logical that it could work.

**Comment by mpirri** [comment]
Thanks so much for the PR, sorry for (another!) late reply! Definitely agree with your latest comment about splitting the xcode build into two separate invocations of xcodebuild.

My feeling is that I don't think this PR runs a high risk of re-introducing issue https://github.com/fastlane/snapshot/issues/246.

Are you interested in attempting to create a PR with the solutions you proposed back on January 20? If not, that's okay, too.

Thanks for taking the time to look into this; I'm going to close it for now, feel free to re-submit or reply if you think this was in error.

**Pull request closed without merging**
