### PR TITLE
Adding keyboard navigation to screenshot HTML file

### PR DESCRIPTION
**Pull request by powtac**
Hack for left arrow keyboard navigation. References #69

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @powtac, I don't know when that happens, but right now the HTML page is pretty broken regarding the light box and arrow + ESC keys. If you have some time I'd appreciate if you could take a quick look :+1:

**Comment by powtac** [comment]
Hi @krausefx, can you please append a rendered HTML page to this ticket? At the very moment I don't have a working installation near me.

**Comment by KrauseFx** [comment]
@powtac yes sure: https://www.dropbox.com/s/lfn7jye99kjy3zd/ScreenshotsExample.zip?dl=0

**Comment by powtac** [comment]
@KrauseFx you can delete the Dropbox Zip file.

**Comment by KrauseFx** [comment]
Thanks @powtac :+1:

**Pull request merged**
