### PR TITLE
Fix for UI elements recognising the swipe gesture

### LINKED ISSUE #215: [UI Testing] Snapshot helper clicks item on tabBar
When using the snapshot helper on an application that has a tabBar on it the lower right object is clicked erroneously.

I have created a simple example application showing this, https://github.com/davidrothera/snapshot_test run snapshot on that application and you will see it clicks into the second view controller.

### PR DESCRIPTION
**Pull request by dave-perry**
Fixes #215, #276, #306

### CODE REVIEW

**Comment by KrauseFx** [comment]
Correct me if I'm wrong, but this will just tap somewhere else and doesn't fix the underlying issue, right? It will now tap on the bottom left corner.

**Comment by InsertWittyName** [comment]
It does tap somewhere else, but it doesn't hit a tab button or nav bar button from my testing, which fixes the underlying problem until an alternative can be considered.

**Comment by emarley** [comment]
This workaround does also solve the issue for my app with both a nav bar and a bottom bar. 

If patching this by replacing one pair of magic numbers with another is uncomfortable, could it be worth making those coordinates configurable in the Snapfile?

**Comment by KrauseFx** [comment]
I cannot just merge this, as it would break existing setups, since the `SnapshotHelper.swift` was copied over to the project already.

**Comment by KrauseFx** [comment]
@emarley I like the idea of being able to configure this value.

**Comment by KrauseFx** [comment]
Thanks for the pull request, this is now fixed with https://github.com/fastlane/snapshot/releases/tag/1.2.0 :+1:

**Pull request closed without merging**
