### PR TITLE
Update SnapshotHelper.js

### PR DESCRIPTION
**Pull request by larryonoff**
# Critical change of SnapshotHelper.js methods signature
# Added `Snapshot.language()` method

### CODE REVIEW

**Comment by KrauseFx** [comment]
Could you provide information about why you want this change and what it fixes/improves?

**Comment by KrauseFx** [comment]
Why is it critical

**Comment by larryonoff** [comment]
Sorry for confusion. I would better say that it's breaking change.
I have changed the signature of the SnapshotHelper.js methods so now you should call them with Snapshot prefix, e.g. ```Snapshot.captureLocalizedScreenshot(name)```.

**Comment by KrauseFx** [comment]
Closing in favor of https://github.com/KrauseFx/snapshot/releases/tag/1.0.0

**Pull request closed without merging**
