### PR TITLE
Support Objective C

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
Move the logic into a class which can then be accessed by ObjC
[Snapshot setLanguage:]
The global functions are maintained.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, thanks. We also need to update the docs to describe how to use it with Objective C, right?

**Comment by ConfusedVorlon** [comment]
yup - I'll do that now.

**Comment by KrauseFx** [comment]
Cool, thanks @ConfusedVorlon :+1:

**Comment by KrauseFx** [comment]
I already pushed a new version with Objective-C support

**Comment by ConfusedVorlon** [comment]
Clearly twitter isn't slowing you down!

**Pull request merged**
